name: "Setup"
runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt
      shell: bash
    - name: Install JS dependencies
      run: jlpm
      shell: bash
      