name: Build and Publish Extension

on:
  push:
    tags: 'v*'

jobs:

  Test:
    uses: ./.github/workflows/test.yml
    
  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        
      - name: Custom Setup
        uses: ./.github/actions/setup
        
      - name: Build sdist
        run: |
          pip install build
          python -m build --sdist
          
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
