name: Test

on:
  push:
    branches: master
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  Test:
    name: Test
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.12"]
        node-version: ["18.x", "20.x"]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest  
        
      - name: Custom Setup
        uses: ./.github/actions/setup
        
      - name: Test
        uses: ./.github/actions/test
        
      - name: Build
        uses: ./.github/actions/build-ext
        
      - name: Post Test
        env:
            JLAB_BROWSER_TYPE: firefox
        uses: ./.github/actions/post-test

